### ISSUE TITLE
ValueError: Shapes (None, 2) and (None, 1) are incompatible

### ISSUE THREAD

**Issue by HoaiAn0906** [naseemap47/FaceRecognition-MTCNN-ArcFace#10]
Hello!
I thank you for sharing. But when I execute train model, I get the same error. Please show me how to fix it. Thank you
![image](https://user-images.githubusercontent.com/98022590/218536908-652b3f1d-fc22-4d03-800f-7071f28cae0a.png)
![image](https://user-images.githubusercontent.com/98022590/218536946-1c2f9482-7787-42d3-b791-d95ac46e5178.png)

**Comment by naseemap47** [comment]
The issue is fixed or NOT?

**Comment by HoaiAn0906** [comment]
I have fixed the problem. Thank you very much. But may I ask? I tested with
data of 3 people, each person 100 photos taken with laptop webcam. When I
ask an outsider who doesn't have data in the model to test, there is a case
where it misidentifies and returns someone in the model. I need to be more
precise. Thank you very much for reading my email. Have a good day.

Vào Th 3, 14 thg 2, 2023 vào lúc 12:53 NASEEM A P <
***@***.***> đã viết:

**Comment by naseemap47** [comment]
If you add more people data, it will improve the accuracy.
Just try with 10 people and try to predict an unknown person.
Just let me know performance of the model.

How is the inference speed?
